#!/usr/bin/make -f

all: directory requestor utils validator verifier

directory:
	$(MAKE) -C directory

requestor:
	$(MAKE) -C requestor

utils:
	$(MAKE) -C utils

validator:
	$(MAKE) -C validator

verifier:
	$(MAKE) -C verifier

.PHONY: all directory requestor utils validator verifier
